// flow-typed signature: 1823c32999b9aa6891f1e06c5ddbe379
// flow-typed version: <<STUB>>/@backtrack/core_v^0.1.27/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@backtrack/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@backtrack/core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@backtrack/core/dist/backtrack' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/clean/clean' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/cli/cli' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/cli/start' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/config-manager/config-manager' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/config-manager/group-custom-configs' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/config-manager/merge-custom-configs' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/config/env' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/config/paths' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/file-manager/backup-changed-files' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/file-manager/copy-files' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/file-manager/file-manager' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/file-manager/file-test-utils' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/file-manager/get-file-stats' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/file-manager/remove-stale-directories' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/file-manager/remove-stale-files' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/initialize/initialize' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/options-file/clean-preprocessor' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/options-file/clean-processor' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/options-file/clean-validator' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/options-file/files-post-processor' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/options-file/files-preprocessor' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/options-file/files-validator' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/options-file/load-options-file' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/options-file/options-file' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/options-file/package-json-schema' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/options-file/post-processor' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/options-file/preprocessor' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/options-file/preset-validator' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/options-file/resolve-processor' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/options-file/transform-config' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/package-json-manager/backup-package-json' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/package-json-manager/get-managed-keys' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/package-json-manager/load-package-json' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/package-json-manager/package-json-manager' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/package-json-manager/remove-null-values' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/package-json-manager/should-update' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/package-json-manager/sort-package-json' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/package-json-manager/update-package-json' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/package-json-manager/write-package-json' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/pkg/pkg' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/run/run-shell-command' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/run/run' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/run/validate-task' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/stats-file/load-stats-file' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/stats-file/normalize-stats' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/stats-file/write-stats-file' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/types' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/utils/backup-file' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/utils/copy-format-mock-calls' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/utils/copy' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/utils/file-is-inside-dir' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/utils/get-file-hash' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/utils/get-random-number' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/utils/get-type' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/utils/handle-error' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/utils/log' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/utils/make-dirs' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/utils/normalize-pathname' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/utils/object-utils' {
  declare module.exports: any;
}

declare module '@backtrack/core/dist/utils/parse-file-path' {
  declare module.exports: any;
}

declare module '@backtrack/core/paths' {
  declare module.exports: any;
}

// Filename aliases
declare module '@backtrack/core/dist/backtrack.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/backtrack'>;
}
declare module '@backtrack/core/dist/clean/clean.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/clean/clean'>;
}
declare module '@backtrack/core/dist/cli/cli.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/cli/cli'>;
}
declare module '@backtrack/core/dist/cli/start.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/cli/start'>;
}
declare module '@backtrack/core/dist/config-manager/config-manager.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/config-manager/config-manager'>;
}
declare module '@backtrack/core/dist/config-manager/group-custom-configs.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/config-manager/group-custom-configs'>;
}
declare module '@backtrack/core/dist/config-manager/merge-custom-configs.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/config-manager/merge-custom-configs'>;
}
declare module '@backtrack/core/dist/config/env.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/config/env'>;
}
declare module '@backtrack/core/dist/config/paths.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/config/paths'>;
}
declare module '@backtrack/core/dist/file-manager/backup-changed-files.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/file-manager/backup-changed-files'>;
}
declare module '@backtrack/core/dist/file-manager/copy-files.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/file-manager/copy-files'>;
}
declare module '@backtrack/core/dist/file-manager/file-manager.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/file-manager/file-manager'>;
}
declare module '@backtrack/core/dist/file-manager/file-test-utils.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/file-manager/file-test-utils'>;
}
declare module '@backtrack/core/dist/file-manager/get-file-stats.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/file-manager/get-file-stats'>;
}
declare module '@backtrack/core/dist/file-manager/remove-stale-directories.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/file-manager/remove-stale-directories'>;
}
declare module '@backtrack/core/dist/file-manager/remove-stale-files.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/file-manager/remove-stale-files'>;
}
declare module '@backtrack/core/dist/initialize/initialize.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/initialize/initialize'>;
}
declare module '@backtrack/core/dist/options-file/clean-preprocessor.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/options-file/clean-preprocessor'>;
}
declare module '@backtrack/core/dist/options-file/clean-processor.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/options-file/clean-processor'>;
}
declare module '@backtrack/core/dist/options-file/clean-validator.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/options-file/clean-validator'>;
}
declare module '@backtrack/core/dist/options-file/files-post-processor.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/options-file/files-post-processor'>;
}
declare module '@backtrack/core/dist/options-file/files-preprocessor.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/options-file/files-preprocessor'>;
}
declare module '@backtrack/core/dist/options-file/files-validator.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/options-file/files-validator'>;
}
declare module '@backtrack/core/dist/options-file/load-options-file.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/options-file/load-options-file'>;
}
declare module '@backtrack/core/dist/options-file/options-file.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/options-file/options-file'>;
}
declare module '@backtrack/core/dist/options-file/package-json-schema.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/options-file/package-json-schema'>;
}
declare module '@backtrack/core/dist/options-file/post-processor.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/options-file/post-processor'>;
}
declare module '@backtrack/core/dist/options-file/preprocessor.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/options-file/preprocessor'>;
}
declare module '@backtrack/core/dist/options-file/preset-validator.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/options-file/preset-validator'>;
}
declare module '@backtrack/core/dist/options-file/resolve-processor.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/options-file/resolve-processor'>;
}
declare module '@backtrack/core/dist/options-file/transform-config.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/options-file/transform-config'>;
}
declare module '@backtrack/core/dist/package-json-manager/backup-package-json.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/package-json-manager/backup-package-json'>;
}
declare module '@backtrack/core/dist/package-json-manager/get-managed-keys.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/package-json-manager/get-managed-keys'>;
}
declare module '@backtrack/core/dist/package-json-manager/load-package-json.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/package-json-manager/load-package-json'>;
}
declare module '@backtrack/core/dist/package-json-manager/package-json-manager.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/package-json-manager/package-json-manager'>;
}
declare module '@backtrack/core/dist/package-json-manager/remove-null-values.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/package-json-manager/remove-null-values'>;
}
declare module '@backtrack/core/dist/package-json-manager/should-update.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/package-json-manager/should-update'>;
}
declare module '@backtrack/core/dist/package-json-manager/sort-package-json.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/package-json-manager/sort-package-json'>;
}
declare module '@backtrack/core/dist/package-json-manager/update-package-json.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/package-json-manager/update-package-json'>;
}
declare module '@backtrack/core/dist/package-json-manager/write-package-json.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/package-json-manager/write-package-json'>;
}
declare module '@backtrack/core/dist/pkg/pkg.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/pkg/pkg'>;
}
declare module '@backtrack/core/dist/run/run-shell-command.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/run/run-shell-command'>;
}
declare module '@backtrack/core/dist/run/run.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/run/run'>;
}
declare module '@backtrack/core/dist/run/validate-task.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/run/validate-task'>;
}
declare module '@backtrack/core/dist/stats-file/load-stats-file.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/stats-file/load-stats-file'>;
}
declare module '@backtrack/core/dist/stats-file/normalize-stats.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/stats-file/normalize-stats'>;
}
declare module '@backtrack/core/dist/stats-file/write-stats-file.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/stats-file/write-stats-file'>;
}
declare module '@backtrack/core/dist/types.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/types'>;
}
declare module '@backtrack/core/dist/utils/backup-file.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/utils/backup-file'>;
}
declare module '@backtrack/core/dist/utils/copy-format-mock-calls.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/utils/copy-format-mock-calls'>;
}
declare module '@backtrack/core/dist/utils/copy.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/utils/copy'>;
}
declare module '@backtrack/core/dist/utils/file-is-inside-dir.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/utils/file-is-inside-dir'>;
}
declare module '@backtrack/core/dist/utils/get-file-hash.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/utils/get-file-hash'>;
}
declare module '@backtrack/core/dist/utils/get-random-number.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/utils/get-random-number'>;
}
declare module '@backtrack/core/dist/utils/get-type.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/utils/get-type'>;
}
declare module '@backtrack/core/dist/utils/handle-error.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/utils/handle-error'>;
}
declare module '@backtrack/core/dist/utils/log.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/utils/log'>;
}
declare module '@backtrack/core/dist/utils/make-dirs.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/utils/make-dirs'>;
}
declare module '@backtrack/core/dist/utils/normalize-pathname.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/utils/normalize-pathname'>;
}
declare module '@backtrack/core/dist/utils/object-utils.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/utils/object-utils'>;
}
declare module '@backtrack/core/dist/utils/parse-file-path.js' {
  declare module.exports: $Exports<'@backtrack/core/dist/utils/parse-file-path'>;
}
declare module '@backtrack/core/paths.js' {
  declare module.exports: $Exports<'@backtrack/core/paths'>;
}
