// flow-typed signature: 4658539187a87840472701fa54184e95
// flow-typed version: <<STUB>>/resolve-with-prefix_v^2.0.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'resolve-with-prefix'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'resolve-with-prefix' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'resolve-with-prefix/dist/create-resolver' {
  declare module.exports: any;
}

declare module 'resolve-with-prefix/dist/get-list-of-package-ids' {
  declare module.exports: any;
}

declare module 'resolve-with-prefix/dist/resolve-with-prefix-async' {
  declare module.exports: any;
}

declare module 'resolve-with-prefix/dist/resolve-with-prefix-sync' {
  declare module.exports: any;
}

declare module 'resolve-with-prefix/dist/resolve-with-prefix' {
  declare module.exports: any;
}

declare module 'resolve-with-prefix/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'resolve-with-prefix/dist/create-resolver.js' {
  declare module.exports: $Exports<'resolve-with-prefix/dist/create-resolver'>;
}
declare module 'resolve-with-prefix/dist/get-list-of-package-ids.js' {
  declare module.exports: $Exports<'resolve-with-prefix/dist/get-list-of-package-ids'>;
}
declare module 'resolve-with-prefix/dist/resolve-with-prefix-async.js' {
  declare module.exports: $Exports<'resolve-with-prefix/dist/resolve-with-prefix-async'>;
}
declare module 'resolve-with-prefix/dist/resolve-with-prefix-sync.js' {
  declare module.exports: $Exports<'resolve-with-prefix/dist/resolve-with-prefix-sync'>;
}
declare module 'resolve-with-prefix/dist/resolve-with-prefix.js' {
  declare module.exports: $Exports<'resolve-with-prefix/dist/resolve-with-prefix'>;
}
declare module 'resolve-with-prefix/dist/utils.js' {
  declare module.exports: $Exports<'resolve-with-prefix/dist/utils'>;
}
